### ISSUE TITLE
添加音乐报错

### ISSUE THREAD

**Issue by LYC945** [itning/yunshu-nas#1107]
java.lang.NullPointerException: Cannot invoke "top.itning.yunshunas.music.config.DataSourceConfig$DataSourceWrapper.dataSource()" because the return value of "java.util.Map.get(Object)" is null

![截屏2024-06-29 下午12 01 11](https://github.com/itning/yunshu-nas/assets/111118178/88903fc6-5440-4e26-8a63-866212e69a5d)

**Comment by itning** [comment]
数据源配置了吗

**Comment by itning** [comment]
已经修复了
