### ISSUE TITLE
几个疑问

### ISSUE THREAD

**Issue by Taogang00** [itning/yunshu-nas#2]
1.这个可以改成HLS+mp4+OOS 点播吗，现在只想HLS 拉流实现播放OOS上的mp4文件
2.ffmpeg是否可以通过maven引入的方式来做转化？我看有
    	<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.1-1.4.4</version>
        </dependency>
依赖，针对不同环境有不同的SDK
3.谢谢，刚入坑 。。

**Comment by itning** [comment]
1. 因为MP4只是封装格式，编码有很多种，当初选择所有视频都转成HLS是为了都能够播放和文件断点续传
2. 可以，没选择maven的原因是文件有点大和想手动调用，未来会用JNI形式，但是目前够用
3. 不用谢
