### ISSUE TITLE
请问保存数据库配置一直转圈是什么问题？

### ISSUE THREAD

**Issue by sifanx** [itning/yunshu-nas#801]
`docker run --name yunshu-nas -p 8888:8888 itning/yunshu-nas:latest`
`nohup java -jar yunshu-nas.jar >log.log 2>&1 &`
`nohup aria2c --rpc-listen-port 6800 --enable-rpc --rpc-listen-all >aria2c.log 2>&1 &`
将上述几条命令执行后，访问网页，能正常打开，但是在保存数据库配置的时候，一直转圈圈，不知道什么情况，地址、端口、账号和密码确认是对的，用Navicat工具能登录，JDK17也装过了，是我哪里填错了吗？

[root@AlmaLinux ~]# java -version
openjdk version "17.0.9" 2023-10-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-1) (build 17.0.9+9-LTS, mixed mode, sharing)

![db](https://github.com/itning/yunshu-nas/assets/42561369/1dd261d1-ea4b-4b75-9b31-9e966004a74f)

**Comment by itning** [comment]
直接保持试下呢

**Comment by sifanx** [comment]
> 直接保持试下呢

直接保存也是这样的呢
