### ISSUE TITLE
太不走心了

### ISSUE THREAD

**Issue by lixiaoyu0123** [itning/yunshu-nas#898]
容器应该没做测试
问题如下：
1. 前端页面配置，没有支持远程配置，不应该js里面写死localhost:8888，有的场景可能是远程的服务器地址。不是本地的。
2. 容器中竟然提示mysql driver没有安装。这么严重的问题没有处理。

**Comment by itning** [comment]
再试下
``shell
docker run --name yunshu-nas -p 8888:8888 -e SERVER_URL=http://localhost:8888 itning/yunshu-nas:latest
``
