### ISSUE TITLE
org.springframework.web.context.request.async.AsyncRequestNotUsableException: ServletOutputStream failed to write: 你的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by scyslz** [itning/yunshu-nas#980]
视频出不来转圈圈, 这是怎么回事
![image](https://github.com/itning/yunshu-nas/assets/39955047/7721515a-b533-4ce9-87fa-3771c14a160d)

ENV OpenJDK21

**Comment by itning** [comment]
看下你的视频是什么编码的？
